services:
  capjs:
    build: capjs/standalone
    # restart: unless-stopped
    user: "1000:1000"   # stesso utente dell'init
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://valkey:6379
      # in produzione spostare su un secret/vault
      ADMIN_KEY: your_secret_password_your_secret_password
      WIDGET_VERSION: 0.1.33
      WASM_VERSION: 0.0.6
      ENABLE_ASSETS_SERVER: true
      CORS_ORIGIN: "*"
      LOGIN_PAGE_ENABLED: true
      HIDE_RATELIMIT_IP_WARNING: true
    depends_on:
      valkey:
        condition: service_healthy

  valkey:
    image: valkey/valkey:9-alpine
    volumes:
      - valkey-data:/data
    command: valkey-server --save 60 1 --loglevel warning --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  demo:
    build: ./demo
    user: "1000:1000"
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/shared
    depends_on:
      - demo-init

  demo-init:
    build: ./demo-init
    user: "1000:1000"
    volumes:
      - ./shared:/shared
    environment:
      CAPJS_URL: http://capjs:3000
      ADMIN_KEY: your_secret_password_your_secret_password
    restart: "no"
    depends_on:
      - capjs

volumes:
  valkey-data:
